# Generated by Django 6.1.1 on 2026-09-29 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cuit', models.CharField(max_length=20, unique=True)),
                ('direccion_fiscal', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tipo', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='ordenVenta.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_entrega_prometida', models.DateTimeField(blank=True, null=True)),
                ('lugar_entrega', models.CharField(blank=True, max_length=255)),
                ('notas_instalacion', models.TextField(blank=True)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('porcentaje_con_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_venta', to='ordenVenta.cliente')),
            ],
        ),
    ]
