# Generated by Django 6.1.1 on 2026-09-29 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenVenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_apertura', models.CharField(max_length=100)),
                ('estilo', models.CharField(max_length=100)),
                ('vidrio', models.CharField(max_length=100)),
                ('linea_accesorios', models.CharField(max_length=100)),
                ('tapa_junta', models.CharField(max_length=100)),
                ('revestimiento', models.CharField(max_length=100)),
                ('marco', models.CharField(max_length=100)),
                ('color_carpinteria', models.CharField(max_length=100)),
                ('adicionales', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('orden_venta', models.ForeignKey(db_column='id_orden_venta', on_delete=django.db.models.deletion.CASCADE, related_name='disenos', to='ordenVenta.ordenventa')),
            ],
        ),
    ]
