# Generated by Django 6.1.1 on 2026-09-29 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Apertura_cajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.CharField(max_length=500)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Apertura_caja', to='cajas.cajas')),
            ],
        ),
        migrations.CreateModel(
            name='Cierre_Cajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('monto_cierre_sistema', models.DecimalField(decimal_places=2, max_digits=11)),
                ('monto_fisico', models.DecimalField(decimal_places=2, max_digits=11)),
                ('observaciones', models.CharField(max_length=500)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Cierre_cajas', to='cajas.cajas')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento_Cajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=100)),
                ('concepto', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('num_comprobante', models.CharField(blank=True, max_length=50)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_Cajas', to='cajas.cajas')),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos_cajas', to='roles.usuarios')),
            ],
        ),
    ]
