# Generated by Django 6.1.1 on 2026-09-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento_cajas',
            name='usuario_asignado',
        ),
    ]
